--- 
description: "First steps to trying out blogging"
excerpt_separator: ""
markdown: kramdown
paginate: 5
pygments: true
tagline: "Random thoughts on programming"
title: "Pär Björklund"
url: "http://Paxxi.github.io"
