--- 
description: "Things that are interesting or useful to me"
excerpt_separator: ""
markdown: kramdown
paginate: 5
highlighter: rouge
tagline: "Random thoughts on programming"
title: "Paxxis soapbox"
url: "http://Paxxi.github.io"
theme: jekyll-theme-cayman
